#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="$(getApplication)"

cp -r initial 0
runApplication blockMesh 
runApplication setSolidFraction
runApplication transformPoints "rotate=((0 1 0) (0 0 1))" 
transformPoints "translate=(-0.00005 0 0)"
#runApplication laserbeamFoam
#------------------------------------------------------------------------------
