#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

targetType=""

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

(cd laserHeatSource && ./Allwmake $targetType $* 2>&1 | tee log.Allwmake)
