#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set up initial conditions
application="$(getApplication)"

cp -r initial 0

runApplication blockMesh

runApplication setFields
 
runApplication decomposePar

runParallel $application

runApplication reconstructParMesh

runApplication reconstructPar

                                                                                                                                                         
#------------------------------------------------------------------------------
