#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Set up initial conditions
application="$(getApplication)"


# refinement stuff to run topoSet
refineMeshByCellSet()
{
   while [ $# -ge 1 ]
   do
      if [ ! -e log.refineMesh.$1 ]
      then
          echo "Creating cell set for primary zone - $1"
          cp system/topoSetDict.$1 system/topoSetDict
          topoSet > log.topoSet.$1 2>&1

          echo "Refining primary zone - $1"
          refineMesh -dict system/refineMeshDict -overwrite \
              > log.refineMesh.$1 2>&1
      fi
      shift
   done
}



cp -r initial 0

runApplication blockMesh

refineMeshByCellSet 1 2

runApplication setFields

runApplication decomposePar

runParallel $application

runApplication reconstructPar


#------------------------------------------------------------------------------
