#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

echo "Copying 'initial' to 0"
cp -r initial 0

runApplication blockMesh
runApplication setFields
runApplication array_laserbeamFoam
